package web.compose.material3.example

import org.jetbrains.compose.web.css.Color
import web.compose.material3.theming.SysColorScheme

val greenishColorScheme = SysColorScheme(
    sysColorPrimary = Color("#006A6A"),
    sysColorPrimaryContainer = Color("#6FF7F6"),
    sysColorOnPrimary = Color("#FFFFFF"),
    sysColorOnPrimaryContainer = Color("#002020"),
    sysColorSecondary = Color("#4A6363"),
    sysColorSecondaryContainer = Color("#CCE8E7"),
    sysColorOnSecondary = Color("#FFFFFF"),
    sysColorOnSecondaryContainer = Color("#051F1F"),
    sysColorTertiary = Color("#4B607C"),
    sysColorTertiaryContainer = Color("#D3E4FF"),
    sysColorOnTertiary = Color("#FFFFFF"),
    sysColorOnTertiaryContainer = Color("#041C35"),
    sysColorError = Color("#BA1A1A"),
    sysColorErrorContainer = Color("#FFDAD6"),
    sysColorOnError = Color("#FFFFFF"),
    sysColorOnErrorContainer = Color("#410002"),
    sysColorOutline = Color("#6F7979"),
    sysColorBackground = Color("#FAFDFC"),
    sysColorOnBackground = Color("#191C1C"),
    sysColorSurface = Color("#FAFDFC"),
    sysColorOnSurface = Color("#191C1C"),
    sysColorSurfaceVariant = Color("#DAE5E4"),
    sysColorOnSurfaceVariant = Color("#3F4948"),
    sysColorSurfaceContainerLowest = Color("#FFFFFF"),
    sysColorInverseSurface = Color("#2D3131"),
    sysColorInverseOnSurface = Color("#EFF1F0"),
    sysColorInversePrimary = Color("#4CDADA"),
    sysColorShadow = Color("#000000"),
    sysColorSurfaceTint = Color("#006A6A"),
    sysColorOutlineVariant = Color("#BEC9C8"),
    sysColorScrim = Color("#000000")
)

val alternativeDarkColorScheme = SysColorScheme(
    sysColorPrimary = Color("#4CDADA"),
    sysColorPrimaryContainer = Color("#004F4F"),
    sysColorOnPrimary = Color("#003737"),
    sysColorOnPrimaryContainer = Color("#6FF7F6"),
    sysColorSecondary = Color("#B0CCCB"),
    sysColorSecondaryContainer = Color("#324B4B"),
    sysColorOnSecondary = Color("#1B3534"),
    sysColorOnSecondaryContainer = Color("#CCE8E7"),
    sysColorTertiary = Color("#B3C8E8"),
    sysColorTertiaryContainer = Color("#334863"),
    sysColorOnTertiary = Color("#1C314B"),
    sysColorOnTertiaryContainer = Color("#D3E4FF"),
    sysColorError = Color("#FFB4AB"),
    sysColorErrorContainer = Color("#93000A"),
    sysColorOnError = Color("#690005"),
    sysColorOnErrorContainer = Color("#FFDAD6"),
    sysColorOutline = Color("#889392"),
    sysColorBackground = Color("#191C1C"),
    sysColorOnBackground = Color("#E0E3E2"),
    sysColorSurface = Color("#191C1C"),
    sysColorOnSurface = Color("#E0E3E2"),
    sysColorSurfaceVariant = Color("#3F4948"),
    sysColorOnSurfaceVariant = Color("#BEC9C8"),
    sysColorSurfaceContainerLowest = Color("#000000"),
    sysColorInverseSurface = Color("#E0E3E2"),
    sysColorInverseOnSurface = Color("#191C1C"),
    sysColorInversePrimary = Color("#006A6A"),
    sysColorShadow = Color("#000000"),
    sysColorSurfaceTint = Color("#4CDADA"),
    sysColorOutlineVariant = Color("#3F4948"),
    sysColorScrim = Color("#000000")
)
