name: Build library

on:
  push:

jobs:
  build-gradle-project:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project sources
        uses: actions/checkout@v3
      - name: Gradle build
        uses: gradle/gradle-build-action@v2
        with:
          arguments: build
          build-root-directory: library
